### PR TITLE
Add io-ts toJsonSchema util

### PR DESCRIPTION
**Pull request by bencmbrook**
Refactored from https://github.com/transcend-io/cli/pull/116#pullrequestreview-1329712453

## Related Issues

- _[none]_

## Security Implications

_[none]_

## System Availability

_[none]_

### CODE REVIEW

**Review by michaelfarrell76 — DISMISSED** [review]
thanks!

**Comment by michaelfarrell76** [comment]
ci may be borked, it may be missing a pinning of the proper node version. would check out the cli ci job and compare to see what’s different

**Comment by bencmbrook** [comment]
Yeah it's broken https://github.com/transcend-io/type-utils/pull/10

**Review by michaelfarrell76 — APPROVED** [review]
thanks!

**Pull request merged**
